### ISSUE TITLE
Error: Could not find or load main class org.codehaus.classworlds.Launcher

### ISSUE THREAD

**Issue by DaveF63** [openstreetmap/osmosis#135]
Hi
Latest .zip download which extracts to osmosis-main\osmosis-main\package\bin returns:
Error: Could not find or load main class org.codehaus.classworlds.Launcher when running osmosis.bat

The previous version (osmosis-0.48.3\lib) runs as expected. 

Any ideas for a solution?

Using Windows 10 Pro 22H2

Edit: To check Is the .zip file behind the green code button not the correct place to download the latest version? (It's where I get all programs for other repositories) Ít extracts to a total of over a thousand files in 429 folders!

**Comment by scrobbleme** [comment]
When you download the "code" you have to compile and package it, before using it. (other repos may work differently, so you can just download it this way)

The correct place for release is: https://github.com/openstreetmap/osmosis/releases
→ 0.48.3 is still the latest released version.

**Comment by brettch** [comment]
It looks like the source version was downloaded instead of the binary release. Please check with the latest release https://github.com/openstreetmap/osmosis/releases/tag/0.49.2 and re-open if it still exists.
