### ISSUE TITLE
0.49.1 release did not complete

### ISSUE THREAD

**Issue by chenrui333** [openstreetmap/osmosis#136]
👋 it looks like 0.49.1 release did not get completed, let me know if that makes sense. Thanks!

**Comment by brettch** [comment]
Hi @chenrui333. I'm not quite sure what you mean. Are you looking for release files on GitHub? If so, the 0.49.0 release is the latest version. 0.49.1 is a minor fix to the Maven Central publishing process. The Osmosis code is identical.
