### ISSUE TITLE
Allow tee to spawn a thread by outPipe

### ISSUE THREAD

**Issue by a14n** [openstreetmap/osmosis#80]
I tried to use `--tee` to create several pbfs from an single pbf source. Currently all outputs are handled sequentially but for independant pipelines it could be worth to proccess them in parallel.

What do you think?

**Comment by brettch** [comment]
Hi, I think you're looking for the (perhaps confusingly named) `--buffer` task.
https://wiki.openstreetmap.org/wiki/Osmosis/Detailed_Usage#--buffer_.28--b.29

Pass each output of the `--tee` task into a separate `--buffer` task and the output of those into your destination tasks.  That will cause each `--tee` output to be processed on a separate thread.
