### ISSUE TITLE
Duplicate work being done on pbf parsing and writing

### ISSUE THREAD

**Issue by simonpoole** [openstreetmap/osmosis#85]
@simon04 @brettch @migurski @joto

Noticed this while updating the dependency for googles protobuf lib for Vespuccii, but I would have screamed before if I had noticed that actual work was being done on https://github.com/openstreetmap/OSM-binary, which iirc was only moved to the openstreetmap org for archival purposes more than half a decade ago.

@brettch pls correct me if I'm wrong, but back when PBF support was integrated in to osmosis, a copy of the code in OSM-binary was integrated instead of adding it as a dependency. So what has happened now is that @simon04 has been working on the code in OSM-binary, with independent parallel now and then changes to the source code here.

Given that OSM doesn't have enough dev time to go around as is, duplicating work makes no sense at all. Unluckily due to the nature of how OSM-binary was integrated there doesn't seem to be a simple solution for projects that have either one or the other integrated, but maybe somebody has a better idea on how to resolve this?

**Comment by simon04** [comment]
I cannot speak for the intended use of the Java code in repository vs. the Java code in OSM-binary. Various GNU/Linux distributions have been providing libosmpbf packages for years, see https://repology.org/project/libosmpbf/versions.

Relevant discussion about releasing OSM-binary to Maven Central: https://github.com/openstreetmap/OSM-binary/issues/19

**Comment by brettch** [comment]
@simonpoole , yes I included a copy of OSM-binary at the time.  It is the same code with a package rename to avoid conflicts.  It's effectively vendored code that I've updated at least once over the years so it's not a fork as such.  I forget the exact history but prior to this things were a bit messy with code and jar files checked in.

I did it at the time so that I could publish Osmosis to Maven Central and include all required dependencies.  I figured it was lower risk to publish a jar under a different package/namespace in case a better supported version was published later (as it now has).

I might be missing something, but now that OSM-binary itself has published to Maven Central (I think I read that elsewhere) it _should_ be fairly simple to update Osmosis to refer to that instead and delete the existing code from Osmosis.

**Comment by simon04** [comment]
@brettch, thank you for the insights. Can you check if [OSM-binary 1.5.0](https://github.com/openstreetmap/OSM-binary/releases/tag/v1.5.0) from [Maven Central](https://repo1.maven.org/maven2/org/openstreetmap/pbf/osmpbf/1.5.0/) is suitable for Osmosis?

**Comment by simonpoole** [comment]
@brettch in principle yes, but for devs that depend on the separately published Osmosis variant (which was more up to date at the time) it's a vanishing dependency, not really an issue for me* as I'm aware of the issue, but everybody else (assuming there are others) will be surprised. 

" assuming that it hasn't acquired any non-Android compatible bits and pieces.

**Comment by brettch** [comment]
@simonpoole, I've [raised a PR](https://github.com/openstreetmap/osmosis/pull/97) to use the OSM-binary from Maven Central.

**Comment by simonpoole** [comment]
I hope "vanishing" means that old version will still be around, just going forward not?

The problem (specifically for me)  is that 

> " assuming that it hasn't acquired any non-Android compatible bits and pieces.

is open and might imply that I can't move.

In any case closing this as the issue itseld been addressed (but might leave me with maintaining a fork).

**Comment by brettch** [comment]
Yes, the old version will always be on Maven Central.

Maintaining a fork sounds annoying, hopefully that doesn't end up being the case.

**Comment by simonpoole** [comment]
> Maintaining a fork sounds annoying, hopefully that doesn't end up being the case.

Unluckily it is just far too easy to venture in to the unsupported realm with Android even with fairly trivial stuff, for example java.io.UncheckedIOException; is only present on from API 24 on (that is Android 7.0, so still quite current).

In any case there is no pressing need right now to update so at least I can kick that can a bit down the road.
