### ISSUE TITLE
Where is PbfWriter?

### ISSUE THREAD

**Issue by Sintrastes** [openstreetmap/osmosis#96]
Note: I am using osmosis version 0.48.3, with the xml and pbf2 packages installed.

I am building up a pipeline programmatically in my application using the osmosis library, and I would like to both be able to read from, and write to pbf format. However, whereas there is a class `PbfReader`, there seems to be no corresponding `PbfWriter` to be found.

The osmosis command line tool can export to pbf format, so presumably this functionality exists somewhere, but I can not for the life of me find it in the osmosis library. Why is there no `PbfWriter` class for this functionality? How can I create a pipeline that writes to pbf format in the current version of the library?

For now I am having to make do with the `XmlWriter` class.

**Comment by brettch** [comment]
Hi @Sintrastes,

The `osmosis-pbf2` project only provides read-only support for PBF files.  The `PbfReader` class corresponds to the `--read-pbf-fast` task.

The `osmosis-pbf` project provides both read and write support for PBF files.  The `crosby.binary.osmosis.OsmosisReader` class corresponds to the `--read-pbf` task.  The `crosby.binary.osmosis.OsmosisSerializer` class corresponds to the `--write-pbf` task.

Why are there two implementations?  Well, it's been many years so my memory might be a little fuzzy :-)  One benefit of the pbf2 implementation as the task name suggests is speed.  It uses a multi-threaded implementation for parsing PBF blocks which can provide significant speed ups.  The original crosby implementation was written to be used in other Java apps (I forget the exact history here) and I found the code fairly tricky to enhance so I wrote my own reader.  I never got around to creating a PBF writer implementation.

Hope that helps.
